singleNumber: singleNumber.cpp
	g++ -pipe -O2 -std=c++11 singleNumber.cpp -lm

reverseString: reverseString.cpp
	g++ -pipe -O2 -std=c++11 reverseString.cpp -lm

array-basic-1: array-basic-1.cpp
	g++ array-basic-1.cpp -lm

addBinary: addBinary.cpp
	g++ -pipe -O2 -std=c++11 addBinary.cpp -lm
	./a.out

run: a.out
	./a.out

.PHONY:clean
clean: 
	rm a.out
